limits = {
    "abrasao": ["LT", 5.5],
    "basicidade": ["GT", 0.95],
    "cfix": ["LTE", 1.26],
    "compressao": ["GT", 290],
    "distribuicao gran": ["GTE", 95],
    "energia_prensa": ["LT", 35],
    "finos": ["LT", 1],
    "taxarp": ["LT", 35],
    "temp_forno":  ('LTE', 180),
    "particulados1": ["LT", 45],
    "particulados2": ["LT", 45],
    "particulados3": ["LT", 45],
    "relacao gran": None,
    "SE PP": None,
    "SUP_SE_PP": None,
    "GRAN PR": None,
    "SE PR": None,
    "gas": None,
    "produtividade filtragem": None,
    "energia_forno": None,
    "energia_moinho": None,
    "custo_GRAN PR": None,
    "custo_SE PR": None,
    "custo_SE PP": None,
    "umidade": None, 
    "torque": None,
    "temp_recirc": None,
    "temp_precipitador_1": None,
    "temp_precipitador_2": None,
    "temp_precipitador_3": None,
    "temp_precipitador_4": None,
    "dens_moinho_1": None,
    "dens_moinho_2": None,
    "dens_moinho_3": None
#     "energia_filtro": None,
}